<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2018-07-21T06:25:32" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Coba Saya" timestamp="2018-07-21T06:25:32" tests="1" failures="1" time="0">
    <testcase name="Coba Saya Login" time="0" classname="Login">
      <failure><![CDATA[CypressError: cy.visit() failed trying to load:

http://otmproduct.cartenzgroup.com/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ETIMEDOUT 13.250.123.109:80

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ETIMEDOUT 13.250.123.109:80
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

    at Object.cypressErr (http://localhost:51004/__cypress/runner/cypress_runner.js:68176:11)
    at Object.throwErr (http://localhost:51004/__cypress/runner/cypress_runner.js:68141:18)
    at Object.throwErrByPath (http://localhost:51004/__cypress/runner/cypress_runner.js:68168:17)
    at http://localhost:51004/__cypress/runner/cypress_runner.js:59012:31
    at visitFailedByErr (http://localhost:51004/__cypress/runner/cypress_runner.js:58623:12)
    at http://localhost:51004/__cypress/runner/cypress_runner.js:59011:22
    at tryCatcher (http://localhost:51004/__cypress/runner/cypress_runner.js:7091:23)
    at Promise._settlePromiseFromHandler (http://localhost:51004/__cypress/runner/cypress_runner.js:5113:31)
    at Promise._settlePromise (http://localhost:51004/__cypress/runner/cypress_runner.js:5170:18)
    at Promise._settlePromise0 (http://localhost:51004/__cypress/runner/cypress_runner.js:5215:10)
    at Promise._settlePromises (http://localhost:51004/__cypress/runner/cypress_runner.js:5290:18)
    at Async._drainQueue (http://localhost:51004/__cypress/runner/cypress_runner.js:2023:16)
    at Async._drainQueues (http://localhost:51004/__cypress/runner/cypress_runner.js:2033:10)
    at Async.drainQueues (http://localhost:51004/__cypress/runner/cypress_runner.js:1907:14)
    at <anonymous>]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Coba akses ke Manajemen Dasbor" timestamp="2018-07-21T06:26:15" tests="1" failures="1" time="0">
    <testcase name="Coba akses ke Manajemen Dasbor Akses Dasbos" time="0" classname="Akses Dasbos">
      <failure><![CDATA[CypressError: Timed out retrying: Expected to find element: '#\31 _menu > span > div > h4', but never found it.
    at Object.cypressErr (http://localhost:51004/__cypress/runner/cypress_runner.js:68176:11)
    at Object.throwErr (http://localhost:51004/__cypress/runner/cypress_runner.js:68141:18)
    at Object.throwErrByPath (http://localhost:51004/__cypress/runner/cypress_runner.js:68168:17)
    at retry (http://localhost:51004/__cypress/runner/cypress_runner.js:61850:16)
    at http://localhost:51004/__cypress/runner/cypress_runner.js:54003:18
    at tryCatcher (http://localhost:51004/__cypress/runner/cypress_runner.js:7091:23)
    at Promise._settlePromiseFromHandler (http://localhost:51004/__cypress/runner/cypress_runner.js:5113:31)
    at Promise._settlePromise (http://localhost:51004/__cypress/runner/cypress_runner.js:5170:18)
    at Promise._settlePromise0 (http://localhost:51004/__cypress/runner/cypress_runner.js:5215:10)
    at Promise._settlePromises (http://localhost:51004/__cypress/runner/cypress_runner.js:5290:18)
    at Async._drainQueue (http://localhost:51004/__cypress/runner/cypress_runner.js:2023:16)
    at Async._drainQueues (http://localhost:51004/__cypress/runner/cypress_runner.js:2033:10)
    at Async.drainQueues (http://localhost:51004/__cypress/runner/cypress_runner.js:1907:14)
    at <anonymous>]]></failure>
    </testcase>
  </testsuite>
</testsuites>